version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hookuser
      - POSTGRES_PASSWORD=hookpass
      - POSTGRES_DB=hookshot_db

  redis:
    image: redis:7-alpine

  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://hookuser:hookpass@db/hookshot_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A app.core.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://hookuser:hookpass@db/hookshot_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

  beat:
    build: .
    command: celery -A app.core.celery_app beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://hookuser:hookpass@db/hookshot_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

volumes:
  postgres_data: